# Generated by Django 2.1.7 on 2019-03-21 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voted_by',
            field=models.ManyToManyField(related_name='vote_posts', through='core.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
