# Generated by Django 2.1.7 on 2019-03-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_voted_by'),
        ('core', '0004_comment_posted_by'),
    ]

    operations = [
    ]
