# Generated by Django 2.1.7 on 2019-03-24 02:32

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File
from django.utils.text import slugify

def load_post_data(apps, schema_editor):
    """ Read a CSV file full of books and insert them into the database."""
    Post = apps.get_model('core', 'Post')
    
    datapath = os.path.join(settings.BASE_DIR, 'images')
    datafile = os.path.join(datapath, 'post_data.csv')
    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:
            print(row, file=open('file.txt', 'w'))
            title = row['title']

            if Post.objects.filter(title=title).count():
                continue
            
            post =Post.objects.create(
                title = row['title'],            
                url = row['url'],
                description = row['description'][:255],
                image_url = row['image_url'],
                slug = slugify(row['title'])[:50],
            )



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190323_1834'),
    ]

    operations = [migrations.RunPython(load_post_data)
    ]
